ASSUME_CUTS_CANNOT_CREATE_NEW_CONCEPTS: false
CACHE_POTENTIAL_PURVIEWS: true
CACHE_REPERTOIRES: true
CACHE_SIAS: false
CACHING_BACKEND: fs
CLEAR_SUBSYSTEM_CACHES_AFTER_COMPUTING_SIA: false
CUT_ONE_APPROXIMATION: false
FS_CACHE_DIRECTORY: __pyphi_cache__
FS_CACHE_VERBOSITY: 0
LOG_FILE: pyphi.log
LOG_FILE_LEVEL: INFO
LOG_STDOUT_LEVEL: WARNING
MAXIMUM_CACHE_MEMORY_PERCENTAGE: 50
MEASURE: EMD
MONGODB_CONFIG:  
  collection_name: cache
  database_name: pyphi
  host: localhost
  port: 27017
NUMBER_OF_CORES: -1
PARALLEL_COMPLEX_EVALUATION: false
PARALLEL_CONCEPT_EVALUATION: false
PARALLEL_CUT_EVALUATION: false
PARTITION_TYPE: BI
PICK_SMALLEST_PURVIEW: false
PRECISION: 6
PRINT_FRACTIONS: true
PROGRESS_BARS: true
REDIS_CACHE: false
REDIS_CONFIG: 
  db: 0 
  host: localhost 
  port: 6379 
  test_db: 1
REPR_VERBOSITY: 2
SINGLE_MICRO_NODES_WITH_SELFLOOPS_HAVE_PHI: false
SYSTEM_CUTS: 3.0_STYLE
USE_SMALL_PHI_DIFFERENCE_FOR_CES_DISTANCE: false
VALIDATE_CONDITIONAL_INDEPENDENCE: true
VALIDATE_SUBSYSTEM_STATES: true
WELCOME_OFF: true